# Generated by Django 3.2.9 on 2021-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64)),
                ('recieve_date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('unit', models.CharField(max_length=15)),
                ('producer', models.CharField(max_length=64)),
            ],
        ),
    ]
