# Generated by Django 3.2.9 on 2021-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
