# Generated by Django 3.2.9 on 2021-11-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categoriesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='unit',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.myappmodel'),
        ),
    ]
