# Generated by Django 3.2.9 on 2021-11-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211130_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='product',
            field=models.ManyToManyField(related_name='cat', to='myapp.MyAppModel'),
        ),
    ]
