# Generated by Django 3.2.9 on 2021-12-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211130_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.myappmodel'),
        ),
    ]
