# Generated by Django 3.2.9 on 2021-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211201_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='product',
            field=models.ManyToManyField(related_name='cat', to='myapp.MyAppModel'),
        ),
    ]
