# Generated by Django 3.2.9 on 2021-12-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211201_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='some_model',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
