# Generated by Django 3.2.9 on 2021-12-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('myapp', '0008_categoriesmodel_some_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappmodel',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
