# Generated by Django 3.2.9 on 2021-12-01 14:06

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_categoriesmodel_some_model'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myappmodel',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='product',
            field=models.ManyToManyField(related_name='product', to='myapp.MyAppModel'),
        ),
    ]
