# Generated by Django 3.2.9 on 2021-12-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20211201_1706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myappmodel',
            managers=[
            ],
        ),
    ]
