# Generated by Django 3.2.9 on 2021-12-02 05:20

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_myappmodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myappmodel',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
